name: prompthsi_cd
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - conda-forge::python=3.10
  - pytorch::pytorch=2.5.1
  - pytorch::pytorch-cuda=12.1
  - pytorch::torchvision=0.20.1
  - conda-forge::scikit-learn
  - conda-forge::matplotlib
  - conda-forge::torchinfo
  - conda-forge::tqdm
  - conda-forge::h5py
  - conda-forge::numpy
  - conda-forge::scipy
  - conda-forge::pip
  - pip:
      - einops
      - pyyaml
      - git+https://github.com/openai/CLIP.git
